### ISSUE TITLE
[meta] marking repo as "public"

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/hippo#163]
Here are the list of tasks required before we mark this as a public repository:

- [x] sign off on the project name (cc @squillace)
- [x] #164
- [x] publish our first release: v0.1.0 https://github.com/deislabs/hippo/milestone/1
- [x] #161
- [x] #165
- [x] write an announcement blog post

I'll create separate ticket items for these tasks and link them back here.

**Comment by bacongobbler** [comment]
done
